version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=lucid
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=datastrike
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"

  