version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=lucid
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=datastrike
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ../../postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22182:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  datastrike-python:
    image: datastrike/python:latest
    build:
      context: ../../datastrike-python-processing/deploy/
      dockerfile: Dockerfile

    command: /bin/bash -c "cd /datastrike-python/ && python3 main.py"
    volumes:
      - ../../datastrike-python-processing/src/:/datastrike-python
      - ../../map/:/map
      - ../../datastrike-python-processing/deploy/datastrike_python_processing.cfg:/datastrike-python/datastrike_python_processing.cfg
    depends_on:
      - kafka

  datastrike-backend:
    image: datastrike/backend:latest
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    volumes:
    # - ../:/home/node/app
    - ../.env.production:/home/node/app/.env
    - ../../map/:/map
    # - ../node_modules:/home/node/app/node_modules
    ports:
    - 3333:3333
    - 9229:9229
    depends_on:
      - db

  nginx:
    image: datastrike/frontend:latest
    ports:
      - 80:80
      - 443:443
    build:
      context: ../../datastrike-frontend/
      dockerfile: Dockerfile
    volumes:
      - ../../datastrike-frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - datastrike-python
      - datastrike-backend